### ISSUE TITLE
What about the dependency array?

### ISSUE THREAD

**Issue by lauraisabelm** [marinawangmw/reactjs-challenge#1]
https://github.com/marinawangmw/reactjs-challenge/blob/0c0db9b2609a4f51e6935b1a4c53652feae2e54c/src/App.tsx#L13

[question] Is there any reason why you don't add a dependency array?

**Comment by marinawangmw** [comment]
Yes, because I only wanted it to execute once when the app starts

**Comment by lauraisabelm** [comment]
Then you should specify an empty array
