### ISSUE TITLE
Prefer not to use uniqid

### ISSUE THREAD

**Issue by edgarbonillag** [marinawangmw/reactjs-challenge#16]
https://github.com/marinawangmw/reactjs-challenge/blob/dcad32d2ccca5cbf889004f7a47501321b609bb2/src/components/collection/Collection.tsx#L18

If the `item` has an unique identifier, like `id`, it is better to use that for assigning key. For example `item.id`

**Comment by marinawangmw** [comment]
I actually had used item.id in the first place but it turns out to be not unique and had a warning on that, that's why I ended up implementing it

**Comment by edgarbonillag** [comment]
Oh I see, thanks for clarifying that :)
