### ISSUE TITLE
Logic verification

### ISSUE THREAD

**Issue by lauraisabelm** [marinawangmw/reactjs-challenge#6]
https://github.com/marinawangmw/reactjs-challenge/blob/0c0db9b2609a4f51e6935b1a4c53652feae2e54c/src/components/collection/Collection.tsx#L13
[question] Is there any possibility that you get an array with length >= 1 and also that the name field of the first element doesn't exist? Or what is the intention behind this logic?

**Comment by marinawangmw** [comment]
Yes, when I request for residents in a planet or characters in an episode and they don't actually have any, the api returns an array with one object where the fields requested are null: `[{ name:null; image:null }]`
