### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lauraisabelm** [marinawangmw/reactjs-challenge#8]
https://github.com/marinawangmw/reactjs-challenge/blob/0c0db9b2609a4f51e6935b1a4c53652feae2e54c/src/components/cardItem/CardItem.tsx#L51
[question] I don't understand what is the intention here. Why do you use `episode && episode` ?

**Comment by marinawangmw** [comment]
I wanted to evaluate the case in which both of the properties are null but it maybe unnecessary...
