### ISSUE TITLE
Organize queries, reducer and actions

### ISSUE THREAD

**Issue by lauraisabelm** [marinawangmw/reactjs-challenge#9]
Normally you don't have all the queries, the reducers and the actions in just one file, it's better to organize this info in separated folders, one for the Apollo part, one for reducers and another one for actions.

**Comment by marinawangmw** [comment]
Actually I usually manage them in separate files like you said but in the course that I have in the platform explained this redux patterm called Duck, that's way I managed it in this way

**Comment by lauraisabelm** [comment]
Oh ok I see, I don't know the content of the course in detail but what I can say is that in the projects we have done we have handled the redux part in separate files.
